import type { GlosariumItem } from "../lib/types";

export const glosarium: GlosariumItem[] = [
  { istilah: "KPR", definisi: "Kredit Pemilikan Rumah — pinjaman bank untuk membeli rumah, dijamin oleh rumah yang dibeli." },
  { istilah: "FLPP", definisi: "Fasilitas Likuiditas Pembiayaan Perumahan — dana murah pemerintah yang disalurkan bank untuk KPR Masyarakat Berpenghasilan Rendah." },
  { istilah: "MBR", definisi: "Masyarakat Berpenghasilan Rendah — kelompok warga dengan penghasilan di bawah batas tertentu yang menjadi sasaran subsidi perumahan." },
  { istilah: "Plafon", definisi: "Batas maksimum pinjaman yang dapat dicairkan bank, dihitung dari harga rumah dikurangi uang muka." },
  { istilah: "DP / Uang Muka", definisi: "Pembayaran awal pembeli kepada penjual/developer, mengurangi plafon dan menentukan besarnya angsuran." },
  { istilah: "Booking Fee", definisi: "Uang pemesanan unit agar rumah dikunci; umumnya dapat dikonversi menjadi bagian DP bila proses selesai." },
  { istilah: "Tenor", definisi: "Jangka waktu pinjaman, biasanya dalam tahun; untuk KPR 5 hingga 20–30 tahun." },
  { istilah: "Suku Bunga Efektif", definisi: "Bunga yang dihitung dari sisa pokok pinjaman sehingga porsi bunga mengecil seiring berjalannya tenor." },
  { istilah: "Suku Bunga Flat", definisi: "Bunga dihitung dari pokok pinjaman awal, membuat angsuran stabil; umum dipakai KPR subsidi." },
  { istilah: "Bunga Floating", definisi: "Suku bunga yang mengikuti pergerakan suku bunga acuan dan dapat berubah berkala setelah masa fixed." },
  { istilah: "Masa Fixed", definisi: "Periode bunga tetap (mis. 1–3 tahun pertama) sebelum beralih ke bunga mengambang." },
  { istilah: "Anuitas", definisi: "Metode perhitungan angsuran tetap; komposisi pokok–bunga berubah, bunga lebih besar di awal." },
  { istilah: "Debitur", definisi: "Pihak yang memperoleh dan wajib melunasi pinjaman kredit dari bank." },
  { istilah: "Kreditur", definisi: "Pihak pemberi pinjaman (bank) yang berhak menerima pembayaran pokok dan bunga." },
  { istilah: "BPHTB", definisi: "Bea Perolehan Hak atas Tanah dan Bangunan — pajak atas peralihan hak properti, ±5% × (harga − NPOPTKP)." },
  { istilah: "NPOPTKP", definisi: "Nilai Perolehan Objek Pajak Tidak Kena Pajak — pengurang harga sebelum dikenai BPHTB, umumnya Rp60 juta." },
  { istilah: "PPJB", definisi: "Perjanjian Jual Beli — kesepakatan pengikatan jual beli sebelum AJB, umum di transaksi properti baru." },
  { istilah: "AJB", definisi: "Akta Jual Beli — akta notaris/PPAT yang menandai peralihan hak milik secara sah." },
  { istilah: "SHM", definisi: "Sertifikat Hak Milik — bukti kepemilikan tanah/bangunan paling kuat secara hukum." },
  { istilah: "SHGB", definisi: "Sertifikat Hak Guna Bangunan — hak mendirikan bangunan di atas tanah; dapat ditingkatkan menjadi SHM." },
  { istilah: "PBG (dulu IMB)", definisi: "Persetujuan Bangunan Gedung — izin resmi pembangunan properti; sebelum 2021 dikenal sebagai IMB (Izin Mendirikan Bangunan)." },
  { istilah: "Notaris / PPAT", definisi: "Pejabat pembuat akta tanah yang mengesahkan transaksi jual beli dan akad kredit properti." },
  { istilah: "Appraisal", definisi: "Penilaian objek properti oleh surveyor untuk menentukan nilai wajar dan plafon pembiayaan bank." },
  { istilah: "LTV", definisi: "Loan to Value — persentase plafon terhadap nilai properti; makin rendah, DP makin besar." },
  { istilah: "SP3K", definisi: "Surat Persetujuan Pemberian Kredit — dokumen resmi bank berisi plafon, bunga, tenor, dan syarat-syarat." },
  { istilah: "SLIK / BI Checking", definisi: "Sistem Layanan Informasi Keuangan — catatan riwayat kreditmu di sistem OJK yang dicek bank." },
  { istilah: "Take Over", definisi: "Memindahkan sisa kredit ke bank lain, umumnya demi bunga lebih rendah." },
  { istilah: "Refinancing", definisi: "Mengajukan pembiayaan ulang dengan rumah sebagai jaminan untuk mendapat dana tunai." },
  { istilah: "Murabahah", definisi: "Akad jual-beli KPR syariah: bank membeli rumah lalu menjual dengan harga jual final yang diangsur." },
  { istilah: "Asuransi Jiwa Kredit", definisi: "Proteksi yang melunasi sisa utang bila debitur meninggal dunia sebelum kredit tuntas." },
  { istilah: "Asuransi Kebakaran", definisi: "Proteksi properti terhadap risiko kebakaran, umumnya wajib menyertai KPR." },
  { istilah: "SiKumbang", definisi: "Portal resmi BP Tapera berisi data pengembang dan stok rumah subsidi untuk KPR FLPP." },
  { istilah: "SiKasep", definisi: "Aplikasi resmi bagi calon debitur: mencari rumah subsidi dan memantau status pengajuan FLPP." },
  { istilah: "BP Tapera", definisi: "Badan Pengelola Tabungan Perumahan Rakyat — lembaga yang mengelola program FLPP sejak 2025." },
  { istilah: "Tapera", definisi: "Tabungan Perumahan Rakyat — program iuran perumahan pekerja (umumnya 3% gaji) yang dananya mendukung pembiayaan perumahan." },
  { istilah: "Penalti Pelunasan", definisi: "Biaya yang dikenakan bank bila KPR dilunasi lebih cepat dari jadwal (umumnya 1–3% sisa pokok, bervariasi per bank)." },
];